/** A real 64x48 baseline JPEG (gradient with a yellow disc), base64: the fixtures cannot encode JPEG themselves. Test-only. */
export const SAMPLE_JPEG_BASE64 =
  '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAA' +
  'AABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAA' +
  'ABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAA' +
  'AAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAA' +
  'AAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAA' +
  'AABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYF' +
  'BAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMK' +
  'ChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAwAEADASIAAhEB' +
  'AxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAYBBwL/xAAjEAACAgICAgIDAQAAAAAAAAABAgAEAxEFBxKBIUFhcZEx/8QAGAEB' +
  'AQEBAQAAAAAAAAAAAAAABQYEBwP/xAAiEQABBAICAgMBAAAAAAAAAAADAAECEQQxBRJx8AZB0fH/2gAMAwEAAhEDEQA/AJSI' +
  'iHiGukmIkyekVndVRSzMdAAbJMvOF6y5O7gXNfz46KsNhGUu/sfAH93NBMgOLHsaVIo5mbagYl7zXWXKUsDZaGfHeVRsoq+D' +
  '+h8g/wB3IN1ZGKupVlOiCNEGIYOQDKbsGVosxVkREaENFGItiJkmRDVeYiv+neLx3Obs3cyq4poPAEb07E6PoAzs04z07ymK' +
  'nzlilmcILiAIT9upOh7BM7NI/n2m2W/bVNXj+2hyy7StJxnuLi8dPnK13CqoLiHzAH+upGz7BWdmnGO4eUxXOdr08LBxTQhy' +
  'Pp2I2PQAmn4qxH5CPTVPfiv2lkPJowtQMRE6yIaEMRIiJNCGq4xFqMyOrIxVlOwQdEGX3C9nclSrJhv18d7x+BkLlHI/J0Qf' +
  '3qQET2LxwMyLRPDs3v3tFlK7aV/zXZ3JXaz4aFfHR8ho5A5dwPwdAD96kC7M7szsWZjsknZJmREMDjcfDj1BBo37vaMOd5bd' +
  'IiZHBDRBiL//2Q=='

export const SAMPLE_JPEG = Uint8Array.from(Buffer.from(SAMPLE_JPEG_BASE64, 'base64'))
export const SAMPLE_JPEG_SIZE = { width: 64, height: 48 }
