// Scaffolds a new feature module under src/modules/<id>/.
//
//   npm run new:module -- <id> ["Sidebar Title"] [--main]
//
// <id>      lowercase kebab-case, e.g. deck-builder (becomes the folder name)
// --main    also create main.ts + shared.ts (main-process half with a ping handler)
//
// The app discovers the new folder automatically; there is no registry to edit.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Keep in sync with MODULE_ID_PATTERN in src/shared/registry.ts.
const MODULE_ID_PATTERN = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)
const withMain = args.includes('--main')
const [id, titleArg] = args.filter((arg) => !arg.startsWith('--'))

function fail(message) {
  console.error(`new-module: ${message}`)
  console.error('Usage: npm run new:module -- <id> ["Sidebar Title"] [--main]')
  process.exit(1)
}

if (!id) fail('missing module id')
if (!MODULE_ID_PATTERN.test(id))
  fail(`"${id}" is not valid: use lowercase kebab-case, e.g. deck-builder`)

const moduleDir = join(root, 'src', 'modules', id)
if (existsSync(moduleDir)) fail(`src/modules/${id} already exists`)

const words = id.split('-')
const pascal = words.map((word) => word[0].toUpperCase() + word.slice(1)).join('')
const title = titleArg ?? words.map((word) => word[0].toUpperCase() + word.slice(1)).join(' ')
if (title.trim() === '' || /[\r\n]/.test(title)) {
  fail('the sidebar title must be a single non-empty line')
}
const quote = (text) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const files = {}

files['ui.tsx'] = `import { Sparkles } from 'lucide-react'
import { defineUiModule } from '@renderer/sdk'
import { ${pascal}View } from './ui/${pascal}View'

export default defineUiModule({
  id: ${quote(id)},
  title: ${quote(title)},
  icon: Sparkles,
  order: 100,
  component: ${pascal}View
})
`

files[`ui/${pascal}View.tsx`] = `import type { ModuleViewProps } from '@renderer/sdk'

export function ${pascal}View(_props: ModuleViewProps) {
  return (
    <div className="page">
      <header className="page__header">
        <p className="eyebrow">Module</p>
        <h1>{${quote(title)}}</h1>
        <p className="lede">
          Generated by npm run new:module. Replace this page with your feature.
        </p>
      </header>
    </div>
  )
}
`

if (withMain) {
  files['shared.ts'] =
    `/** Types and channel names shared by this module's main.ts and ui. Pure data only. */

export const CHANNELS = {
  /** invoke -> string */
  ping: 'ping'
} as const
`

  files['main.ts'] = `import { defineMainModule } from '@main/sdk'
import { CHANNELS } from './shared'

export default defineMainModule({
  id: ${quote(id)},
  activate(ctx) {
    // The UI calls this with: api.invoke(CHANNELS.ping)
    ctx.handle(CHANNELS.ping, () => 'pong')
  }
})
`
}

for (const [relativePath, content] of Object.entries(files)) {
  const target = join(moduleDir, relativePath)
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, content)
  console.log(`created src/modules/${id}/${relativePath}`)
}

console.log(`
Done. "${title}" will appear in the sidebar on the next build or dev start.
Next steps: see agents/MODULES.md (the module checklist), then run "npm run typecheck".`)
