// Mirrors agents/skills/<name>/ into .claude/skills/<name>/ so Claude Code discovers the skills.
// agents/skills/ is the source of truth; .claude/skills/ is generated (never edit it by hand).
//
//   npm run skills:sync              copy skills across (and remove stale synced copies)
//   npm run skills:sync -- --check   exit 1 if .claude/skills is out of date (changes nothing)
//
// Directories in .claude/skills that this script did not create (no marker file) are left alone.
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const MARKER = '.synced-from-agents'
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourceRoot = join(root, 'agents', 'skills')
const targetRoot = join(root, '.claude', 'skills')
const checkOnly = process.argv.includes('--check')

const isDir = (path) => existsSync(path) && statSync(path).isDirectory()

/** Skills are the sub-folders of agents/skills that contain a SKILL.md. */
const skillNames = isDir(sourceRoot)
  ? readdirSync(sourceRoot).filter((name) => existsSync(join(sourceRoot, name, 'SKILL.md')))
  : []

/** Every file under `dir` as { relative path -> contents }, ignoring the marker. */
function snapshot(dir) {
  const files = {}
  const walk = (current) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (entry.name !== MARKER) {
        files[relative(dir, full).replace(/\\/g, '/')] = readFileSync(full, 'utf8').replace(
          /\r\n/g,
          '\n'
        )
      }
    }
  }
  walk(dir)
  return files
}

const sameSnapshot = (a, b) => JSON.stringify(a) === JSON.stringify(b)
const sortKeys = (object) =>
  Object.fromEntries(Object.entries(object).sort(([x], [y]) => x.localeCompare(y)))

const problems = []
const actions = []

for (const name of skillNames) {
  const from = join(sourceRoot, name)
  const to = join(targetRoot, name)
  if (existsSync(to) && !existsSync(join(to, MARKER))) {
    problems.push(`.claude/skills/${name} exists and was not created by this script; skipped`)
    continue
  }
  const upToDate = existsSync(to) && sameSnapshot(sortKeys(snapshot(from)), sortKeys(snapshot(to)))
  if (upToDate) continue
  actions.push({ type: 'copy', name, from, to })
}

// Synced copies whose source skill no longer exists.
if (isDir(targetRoot)) {
  for (const name of readdirSync(targetRoot)) {
    const dir = join(targetRoot, name)
    if (isDir(dir) && existsSync(join(dir, MARKER)) && !skillNames.includes(name)) {
      actions.push({ type: 'remove', name, to: dir })
    }
  }
}

if (checkOnly) {
  for (const problem of problems) console.warn(`warning: ${problem}`)
  if (actions.length === 0 && problems.length > 0) {
    console.error('skills:sync --check: some skills could not be synced (see warnings above)')
    process.exit(1)
  }
  if (actions.length === 0) {
    console.log(`skills:sync --check: .claude/skills is up to date (${skillNames.length} skills)`)
    process.exit(0)
  }
  for (const action of actions) console.error(`out of date: ${action.type} ${action.name}`)
  console.error('Run "npm run skills:sync" to fix.')
  process.exit(1)
}

for (const action of actions) {
  if (action.type === 'copy') {
    rmSync(action.to, { recursive: true, force: true })
    mkdirSync(dirname(action.to), { recursive: true })
    cpSync(action.from, action.to, { recursive: true })
    writeFileSync(
      join(action.to, MARKER),
      'Generated by scripts/sync-skills.mjs from agents/skills. Do not edit here.\n'
    )
    console.log(`synced   ${action.name}`)
  } else {
    rmSync(action.to, { recursive: true, force: true })
    console.log(`removed  ${action.name} (no longer in agents/skills)`)
  }
}
for (const problem of problems) console.warn(`warning: ${problem}`)
console.log(
  `skills:sync: ${skillNames.length} skill(s) in agents/skills, ${actions.length} change(s)`
)
